### ISSUE TITLE
双击打不开怎么办、

### ISSUE THREAD

**Issue by yl-lei** [rebeyond/Behinder#123]
双击打不开怎么办、

**Comment by wbzh0u** [comment]
我也是一样的问题
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/javafx/application/LauncherImpl
        at javafx.application.Application.launch(Application.java:296)
        at net.rebeyond.behinder.ui.Main.main(Main.java:28)
        at net.rebeyond.behinder.ui.Launcher.main(Launcher.java:6)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.application.LauncherImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more

**Comment by Danny259** [comment]
我也是，请问解决了吗
