### ISSUE TITLE
openjdk11 无法启动 Behinder_v3.0_Beta6_win.jar

### ISSUE THREAD

**Issue by XhstormR** [rebeyond/Behinder#135]
openjdk11、openjdk15 试了都报如下错误：
```
Behinder_v3.0_Beta_6_win>"D:\Work\jdk-11\bin\java.exe" -jar Behinder_v3.0_Beta6_win.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/javafx/application/LauncherImpl
        at javafx.application.Application.launch(Application.java:296)
        at net.rebeyond.behinder.ui.Main.main(Main.java:28)
        at net.rebeyond.behinder.ui.Launcher.main(Launcher.java:6)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.application.LauncherImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more

Behinder_v3.0_Beta_6_win>"D:\Work\jdk-15\bin\java.exe" -jar Behinder_v3.0_Beta6_win.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/javafx/application/LauncherImpl
        at javafx.application.Application.launch(Application.java:296)
        at net.rebeyond.behinder.ui.Main.main(Main.java:28)
        at net.rebeyond.behinder.ui.Launcher.main(Launcher.java:6)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.application.LauncherImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more
```

**Comment by Echocipher** [comment]
参考 #115 ，JavaFx 11以后就独立出来了
