### ISSUE TITLE
v11版本内存shell注入完成但连接失败

### ISSUE THREAD

**Issue by pipiping** [rebeyond/Behinder#165]
在tomcat9环境，连接jsp马后，注入内存马，提示注入完成，进入内存马新连接，提示页面存在，但无法获取密钥

**Comment by pipiping** [comment]
beta10下也能浮现该问题，报错：
java.io.IOException: Class not found
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at net.rebeyond.behinder.core.Params.getParamedClass(Params.java:42)
        at net.rebeyond.behinder.utils.Utils.getData(Utils.java:644)
        at net.rebeyond.behinder.utils.Utils.getData(Utils.java:623)
        at net.rebeyond.behinder.core.ShellService.freeFile(ShellService.java:1432)
        at net.rebeyond.behinder.ui.controller.MainController.lambda$injectMemShell$14(MainController.java:473)
        at java.lang.Thread.run(Thread.java:745)
beta7下提示：
       注入完成，但是shell入库失败：\User\rebeyond\JavaNative.dll（系统找不到指定的路径）
使用的java版本是1.8.0_121
切换到最新的java16，无法打开冰蝎

**Comment by rebeyond** [comment]
beta 11 控制台有报错么？

**Comment by pipiping** [comment]
> beta 11 控制台有报错么？

只打印了：
The pre-shared key handshake fails and enters the dynamic key negotiation process.
没有其他报错

**Comment by pipiping** [comment]
另外上述几个测试版本都会有异常： Exception: java.lang.ThreadDeath thrown from the UncaughtExceptionHandler in thread "Thread-6"或"Thread-11"
