### ISSUE TITLE
Archlinux下打开webshell时崩溃

### ISSUE THREAD

**Issue by wolf2333** [rebeyond/Behinder#17]
`(SWT:11543): Gtk-CRITICAL **: 02:38:06.677: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: org.eclipse.swt.SWTError: No more handles because no underlying browser available.
   Please ensure Webkit with its Gtk 3.x bindings installed. Webkit2 API level preferred.

	at org.eclipse.swt.SWT.error(SWT.java:4578)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:125)
	at net.rebeyond.behinder.ui.MainShell.<init>(MainShell.java:162)
	at net.rebeyond.behinder.ui.Main.openShellWindow(Main.java:144)
	at net.rebeyond.behinder.ui.Main.access$1(Main.java:141)
	at net.rebeyond.behinder.ui.Main$2$3.handleEvent(Main.java:219)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	at net.rebeyond.behinder.ui.Main.open(Main.java:135)
	at net.rebeyond.behinder.ui.Main.start(Main.java:81)
	at net.rebeyond.behinder.ui.Starter.main(Starter.java:28)
	... 5 more
`

**Comment by rebeyond** [comment]
OS版本是什么？

**Comment by wolf2333** [comment]
OS: Arch Linux x86_64
DE: Xfce4
问题已解决,安装webkit2gtk即可
