### ISSUE TITLE
fxml.loadException

### ISSUE THREAD

**Issue by Zimang** [rebeyond/Behinder#273]
javafx.fxml.LoadException:
file:/H:/code/pentest/behinder/Behinder.jar!/net/rebeyond/behinder/ui/MainWindow.fxml:45

版本是4.0.6
jdk17
C:\Program Files\OpenLogic\jdk-17.0.5.8-hotspot\bin

详细报错
javafx.fxml.LoadException:
file:/H:/code/pentest/behinder/Behinder.jar!/net/rebeyond/behinder/ui/MainWindow.fxml:45

        at javafx.fxml/javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2707)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2685)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2516)
        at net.rebeyond.behinder.ui.controller.MainController.openShell(MainController.java:1144)
        at net.rebeyond.behinder.ui.controller.MainController.lambda$initShellTable$20(MainController.java:822)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3602)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3906)
        at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1878)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:557)
        at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:943)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml/javafx.fxml.JavaFXBuilderFactory$ObjectBuilderWrapper$ObjectBuilder.build(JavaFXBuilderFactory.java:237)
        at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:774)
        at javafx.fxml/javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2924)
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2639)
        ... 38 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javafx.fxml/javafx.fxml.JavaFXBuilderFactory$ObjectBuilderWrapper$ObjectBuilder.build(JavaFXBuilderFactory.java:229)
        ... 41 more
Caused by: java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: C:\Program Files\OpenLogic\jdk-17.0.5.8-hotspot\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Users\hzm\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\hzm\AppData\Local\Programs\Python\Python37\;H:\dev\py\3.7_installer_version\Scripts\;H:\dev\py\3.7_installer_version\;C:\Program Files\OpenLogic\jdk-17.0.5.8-hotspot\bin;H:\dev\VM\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;H:\Git\cmd;H:\dev\x86_64-12.2.0-release-posix-seh-rt_v10-rev1\mingw64\bin;H:\dev\Git\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\hzm\.jdks\corretto-1.8.0_372\bin_back;H:\dev\Calibre\;H:\dev\sqlmap-master;H:\dev\cmder\bin;H:\dev\py\2.7.6;H:\dev\py\2.7.6\Scripts;C:\Users\hzm\.cargo\bin;C:\Users\hzm\AppData\Local\Microsoft\WindowsApps;;H:\Microsoft VS Code\bin;H:\dev\IntelliJ IDEA 2021.2.2\bin;H:\dev\pycharm\PyCharm 2023.1.3\bin;;.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:166)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
        at javafx.web/com.sun.webkit.WebPage.lambda$static$0(WebPage.java:135)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at javafx.web/com.sun.webkit.WebPage.<clinit>(WebPage.java:134)
        at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:854)
        at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:839)
        at javafx.web/javafx.scene.web.WebView.<init>(WebView.java:271)
        at javafx.web/com.sun.javafx.fxml.builder.web.WebViewBuilder.build(WebViewBuilder.java:66)
        ... 46 more

**Comment by Zimang** [comment]
解决方法就是下一自带javafx的jdk


[[No jfxwebkit in java.library.path](https://stackoverflow.com/questions/73994190/no-jfxwebkit-in-java-library-path)](https://stackoverflow.com/questions/73994190/no-jfxwebkit-in-java-library-path)

> The solution was actually something to do with the JDK I ran it with. It appears that on my M1 Pro Mac, only a "full" JDK that included JavaFX  could run the project properly, irregardless of project. The only JDK  that still includes JavaFX that I could find was [[Liberica JDK](https://bell-sw.com/pages/downloads/)](https://bell-sw.com/pages/downloads/), which still provides "full" JDKs up to JDK 19, which includes JavaFX.
