### ISSUE TITLE
冰蝎4加解密算法通过一致性校验后，JSP木马连接报错（PHP木马成功）

### ISSUE THREAD

**Issue by xiaoluanzzz** [rebeyond/Behinder#300]
一致性校验通过
<img width="1000" alt="图片" src="https://github.com/rebeyond/Behinder/assets/52275891/b4560a49-c04d-4dd2-b143-3c60a23eb47d">
生成PHP木马连接没有任何问题：
<img width="1244" alt="图片" src="https://github.com/rebeyond/Behinder/assets/52275891/1b24fd86-4a39-45bd-815a-cc28b1f13bb5">
JSP木马连接失败，报错javassist.CannotCompileException: [source error];is missing
<img width="1300" alt="图片" src="https://github.com/rebeyond/Behinder/assets/52275891/ead139fa-7ba7-4514-a720-db5985104a21">
而且这个过程中没有任何报文发出，说明客户端走加密函数的时候直接报错了
<img width="1760" alt="图片" src="https://github.com/rebeyond/Behinder/assets/52275891/be0d19aa-68ee-493e-a7d5-864f047b9a5a">
附上加解密算法：
[分段异或.zip](https://github.com/rebeyond/Behinder/files/14398895/default.zip)

**Comment by rebeyond** [comment]
您发给我的邮件已经收到，谢谢！-----------------------------邱永单位：江苏省南京医科大学公共卫生学院流行病与卫生统计学系电话：18994029188地址：江苏省南京市汉中路140号

**Comment by qn9301** [comment]
您好，我已收到您的来信，我会尽快给您回复。

**Comment by Dr-S1x17** [comment]
命令行运行一下，就知道哪里报错了，你这都知道是客户端报错，看运行日志不就可以了

**Comment by rebeyond** [comment]
您发给我的邮件已经收到，谢谢！-----------------------------邱永单位：江苏省南京医科大学公共卫生学院流行病与卫生统计学系电话：18994029188地址：江苏省南京市汉中路140号

**Comment by qn9301** [comment]
您好，我已收到您的来信，我会尽快给您回复。

**Comment by xiaoluanzzz** [comment]
vassist.CannotCompileException: [source error] ; is missing
	at javassist.CtNewMethod.make(CtNewMethod.java:84)
	at javassist.CtNewMethod.make(CtNewMethod.java:50)
	at net.rebeyond.behinder.core.Params.getTransProtocoledClass(Params.java:310)
	at net.rebeyond.behinder.core.Params.getParamedClass(Params.java:351)
	at net.rebeyond.behinder.utils.Utils.getData(Utils.java:567)
	at net.rebeyond.behinder.utils.Utils.getData(Utils.java:639)
	at net.rebeyond.behinder.core.ShellService.echo(ShellService.java:1271)
	at net.rebeyond.behinder.core.ShellService.doConnect(ShellService.java:284)
	at net.rebeyond.behinder.ui.controller.MainWindowController.doConnect(MainWindowController.java:308)
	at net.rebeyond.behinder.ui.controller.MainWindowController.lambda$initControls$4(MainWindowController.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: compile error: ; is missing
	at javassist.compiler.Parser.parseDeclarators(Parser.java:643)
	at javassist.compiler.Parser.parseDeclarationOrExpression(Parser.java:592)
	at javassist.compiler.Parser.parseFor(Parser.java:380)
	at javassist.compiler.Parser.parseStatement(Parser.java:279)
	at javassist.compiler.Parser.parseBlock(Parser.java:307)
	at javassist.compiler.Parser.parseMethod2(Parser.java:172)
	at javassist.compiler.Javac.compileMethod(Javac.java:156)
	at javassist.compiler.Javac.compile(Javac.java:102)
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	... 10 more

**Comment by xiaoluanzzz** [comment]
这能看出个啥呀，冰蝎4也不开源呀 @Dr-S1x17

**Comment by Dr-S1x17** [comment]
都有报错信息了，哥。 javassist不支持 for (a :  b) 写法 @xiaoluanzzz

**Comment by xiaoluanzzz** [comment]
> 都有报错信息了，哥。 javassist不支持 for (a : b) 写法 @xiaoluanzzz

谢谢哥，javassist的问题解决了，但服务端又报错了，研究了几天实在找不到问题所在，再请教一下您

**Comment by xiaoluanzzz** [comment]
[testvvv.txt](https://github.com/rebeyond/Behinder/files/14738344/testvvv.txt)
这是报错

**Comment by Dr-S1x17** [comment]
> [testvvv.txt](https://github.com/rebeyond/Behinder/files/14738344/testvvv.txt) 这是报错

服务端报错你就直接idea 调试jsp就行了，错误断在哪，跟一下传入的数据和函数，百度就能解决了，话说你给我发报错，不给我发原始的jsp shell，我也不知道哪里有问题啊

**Comment by xiaoluanzzz** [comment]
原始JSP：
[testorigin.txt](https://github.com/rebeyond/Behinder/files/14738407/testorigin.txt)

**Comment by xiaoluanzzz** [comment]
解决了上个BUG的算法：
[分段异或2.config.zip](https://github.com/rebeyond/Behinder/files/14738415/2.config.zip)

**Comment by xiaoluanzzz** [comment]
> > [testvvv.txt](https://github.com/rebeyond/Behinder/files/14738344/testvvv.txt) 这是报错
> 
> 服务端报错你就直接idea 调试jsp就行了，错误断在哪，跟一下传入的数据和函数，百度就能解决了，话说你给我发报错，不给我发原始的jsp shell，我也不知道哪里有问题啊

嗯，我只尝试过导出它的class用java调试过，还没试过直接调试jsp，我尝试一下，还是没怎么接触过java，没经验，呜呜

**Comment by xiaoluanzzz** [comment]
> > [testvvv.txt](https://github.com/rebeyond/Behinder/files/14738344/testvvv.txt) 这是报错
> 
> 服务端报错你就直接idea 调试jsp就行了，错误断在哪，跟一下传入的数据和函数，百度就能解决了，话说你给我发报错，不给我发原始的jsp shell，我也不知道哪里有问题啊

其实也调试过了，但classloader里面的执行过程没办法追踪到，在这里就报错了：

**Comment by xiaoluanzzz** [comment]
> > [testvvv.txt](https://github.com/rebeyond/Behinder/files/14738344/testvvv.txt) 这是报错
> 
> 服务端报错你就直接idea 调试jsp就行了，错误断在哪，跟一下传入的数据和函数，百度就能解决了，话说你给我发报错，不给我发原始的jsp shell，我也不知道哪里有问题啊

其实也调试过了，但是classloader里面的执行过程idea追踪不到，在实例化字节码的时候就报错了：
<img width="1720" alt="image" src="https://github.com/rebeyond/Behinder/assets/52275891/5a0bb6f8-c504-498b-bac9-63fa23d59428">然后也尝试过把解密后的字节码导出成.class文件自己反编译，用反编译的代码运行，结果是正常的：
<img width="1758" alt="image" src="https://github.com/rebeyond/Behinder/assets/52275891/84c9938c-6042-4bd3-85e5-4f04595f7e08">
（乱码是加密后的结果，是正常的）
<img width="851" alt="image" src="https://github.com/rebeyond/Behinder/assets/52275891/28f888df-41f0-4036-8265-20b8822218ab">
下面是反编译前的字节码：
[test.class.zip](https://github.com/rebeyond/Behinder/files/14739202/test.class.zip)
反编译源代码可以发现几处Encrypt的调用都是正确的，实参确实都是Byte数组，好像不存在它报错中的问题

**Comment by xiaoluanzzz** [comment]
<img width="1185" alt="image" src="https://github.com/rebeyond/Behinder/assets/52275891/4ae854dc-be16-4d45-aec5-dcf715f4924e">

**Comment by Dr-S1x17** [comment]
> <img alt="image" width="1185" src="https://private-user-images.githubusercontent.com/52275891/316397246-4ae854dc-be16-4d45-aec5-dcf715f4924e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTU1OTUsIm5iZiI6MTcxMTM1NTI5NSwicGF0aCI6Ii81MjI3NTg5MS8zMTYzOTcyNDYtNGFlODU0ZGMtYmUxNi00ZDQ1LWFlYzUtZGNmNzE1ZjQ5MjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA4MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YzBmMjcyMDFhMTZiMDM0OGRlNjg5ZDAxNjhmYjA2Y2EwYmQwODdjOTE5MTgyZTBmZjZkZGZlMDMwZjY3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xY9HZDMS3EiqBO2SCVOCJAeSr8khwy0I2oPkjDat_p8">

盲猜字节码数组有问题，跟一下解密的结果，对比原始的字节码看一下就知道了。原始的如何获取呢？加密选个空的，服务端jsp debug一下获取完整的字节码数组，肯定是不一样的，我这边没详细跟，但我大胆猜一下应该是字节和字符转义出现的问题

**Comment by xiaoluanzzz** [comment]
> > <img alt="image" width="1185" src="https://private-user-images.githubusercontent.com/52275891/316397246-4ae854dc-be16-4d45-aec5-dcf715f4924e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTU1OTUsIm5iZiI6MTcxMTM1NTI5NSwicGF0aCI6Ii81MjI3NTg5MS8zMTYzOTcyNDYtNGFlODU0ZGMtYmUxNi00ZDQ1LWFlYzUtZGNmNzE1ZjQ5MjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA4MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YzBmMjcyMDFhMTZiMDM0OGRlNjg5ZDAxNjhmYjA2Y2EwYmQwODdjOTE5MTgyZTBmZjZkZGZlMDMwZjY3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xY9HZDMS3EiqBO2SCVOCJAeSr8khwy0I2oPkjDat_p8">
> 
> 盲猜字节码数组有问题，跟一下解密的结果，对比原始的字节码看一下就知道了。原始的如何获取呢？加密选个空的，服务端jsp debug一下获取完整的字节码数组，肯定是不一样的，我这边没详细跟，但我大胆猜一下应该是字节和字符转义出现的问题

我对比了一下原始字节码和我导出的字节码的反编译结果，发现两个只有Encypt函数存在差异，其他地方都是一样的：
<img width="1791" alt="image" src="https://github.com/rebeyond/Behinder/assets/52275891/e9d133ed-1a10-4aa8-9af9-2c689bc719f6">
<img width="1770" alt="image" src="https://github.com/rebeyond/Behinder/assets/52275891/ec99e6e6-0915-423e-be1a-28e79aa99928">
这是两个字节码文件反编译后的源代码：
[oringClass.txt](https://github.com/rebeyond/Behinder/files/14751999/oringClass.txt)
[myClass.txt](https://github.com/rebeyond/Behinder/files/14752000/myClass.txt)
