### ISSUE TITLE
使用了XstartOnFirstThread，Mac下运行还是报错

### ISSUE THREAD

**Issue by samshuai** [rebeyond/Behinder#48]
apple@appledeMacBook-Pro bexie % java -XstartOnFirstThread -jar ./Behinder.jar
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.rebeyond.behinder.ui.Starter.addJarToClasspath(Starter.java:87)
	at net.rebeyond.behinder.ui.Starter.main(Starter.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/swt/graphics/Device
	at net.rebeyond.behinder.ui.Starter.main(Starter.java:27)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.graphics.Device
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

**Comment by godspeedcurry** [comment]
同样的问题

**Comment by rebeyond** [comment]
3.0版本已舍弃awt，采用javafx，已不存在这个问题。
