### ISSUE TITLE
Linux 背景色 问题

### ISSUE THREAD

**Issue by B0y1n4o4** [rebeyond/Behinder#6]
如图所示: 

![_ _20181005151020](https://user-images.githubusercontent.com/15306692/46521047-d8173900-c8b0-11e8-997a-acab289a098f.png)

底下和上面的白色问题

双击打开 shell 时，终端报错，不过仍可以正常操作功能
```
SWT Webkit.java Error: Could not find webkit extension. BrowserFunction functionality will not be available. 
(swt version: 4880) SWT Glue code version: 54.0 info: +BrowserFunction/GDBus, +WebkitExtension Folder versioning, +WebKitExtension OSGI support, +setUrl(..postData..), -setCookie(), -getCookie +mouseDown/Focus
WebKit2Gtk version 2.20.2
Please report this issue *with steps to reproduce* via:
 https://bugs.eclipse.org/bugs/enter_bug.cgi?alias=&assigned_to=platform-swt-inbox%40eclipse.org&attach_text=&blocked=&bug_file_loc=http%3A%2F%2F&bug_severity=normal&bug_status=NEW&comment=&component=SWT&contenttypeentry=&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&data=&defined_groups=1&dependson=&description=&flag_type-1=X&flag_type-11=X&flag_type-12=X&flag_type-13=X&flag_type-14=X&flag_type-15=X&flag_type-16=X&flag_type-2=X&flag_type-4=X&flag_type-6=X&flag_type-7=X&flag_type-8=X&form_name=enter_bug&keywords=&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Linux&product=Platform&qa_contact=&rep_platform=PC&requestee_type-1=&requestee_type-2=&short_desc=webkit2_BrowserProblem
For bug report, please atatch this stack trace:
java.lang.Throwable: 
	at org.eclipse.swt.browser.WebKit.getStackTrace(WebKit.java:437)
	at org.eclipse.swt.browser.WebKit.getInternalErrorMsg(WebKit.java:430)
	at org.eclipse.swt.browser.WebKit.access$200(WebKit.java:123)
	at org.eclipse.swt.browser.WebKit$Webkit2Extension.initializeWebExtensions_callback(WebKit.java:532)
	at org.eclipse.swt.internal.webkit.WebKitGTK._webkit_web_view_new(Native Method)
	at org.eclipse.swt.internal.webkit.WebKitGTK.webkit_web_view_new(WebKitGTK.java:1878)
	at org.eclipse.swt.browser.WebKit.create(WebKit.java:1079)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at net.rebeyond.behinder.ui.MainShell.<init>(MainShell.java:160)
	at net.rebeyond.behinder.ui.Main.openShellWindow(Main.java:133)
	at net.rebeyond.behinder.ui.Main.access$1(Main.java:130)
	at net.rebeyond.behinder.ui.Main$2$3.handleEvent(Main.java:205)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4940)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4518)
	at net.rebeyond.behinder.ui.Main.open(Main.java:124)
	at net.rebeyond.behinder.ui.Main.start(Main.java:70)
	at net.rebeyond.behinder.ui.Starter.main(Starter.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

**Comment by rebeyond** [comment]
操作系统是哪个发行版？版本是什么？

**Comment by B0y1n4o4** [comment]
> 操作系统是哪个发行版？版本是什么？

```
$ sudo screenfetch                           
              ............                root@xxxxxx
          .';;;;;.       .,;,.            OS: Deepin 15.7 unstable
       .,;;;;;;;.       ';;;;;;;.         Kernel: x86_64 Linux 4.15.0-29deepin-generic
     .;::::::::'     .,::;;,''''',.       Uptime: 4d 2h 9m
    ,'.::::::::    .;;'.          ';      Packages: 3173
   ;'  'cccccc,   ,' :: '..        .:     Shell: sudo
  ,,    :ccccc.  ;: .c, '' :.       ,;    Resolution: 1366x768
 .l.     cllll' ., .lc  :; .l'       l.   WM: Mutter(DeepinGala)
 .c       :lllc  ;cl:  .l' .ll.      :'   WM Theme: Adwaita
 .l        'looc. .   ,o:  'oo'      c,   CPU: Intel Core i5-4210U @ 4x 2.7GHz [53.5°C]
 .o.         .:ool::coc'  .ooo'      o.   GPU: intel
  ::            .....   .;dddo      ;c    RAM: 3639MiB / 7861MiB
   l:...            .';lddddo.     ,o    
    lxxxxxdoolllodxxxxxxxxxc      :l     
     ,dxxxxxxxxxxxxxxxxxxl.     'o,      
       ,dkkkkkkkkkkkkko;.    .;o;        
         .;okkkkkdl;.    .,cl:.          
             .,:cccccccc:,.              

```
