### ISSUE TITLE
Mac端启动异常

### ISSUE THREAD

**Issue by Arthur-Geng** [rebeyond/Behinder#88]
➜  Behinder_v3.0_Beta_4 java -jar Behinder.jar
错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application
➜  Behinder_v3.0_Beta_4 java -XstartOnFirstThread -jar Behinder.jar
错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main
原因: java.lang.NoClassDefFoundError: javafx/application/Application

JDK版本14

**Comment by Arthur-Geng** [comment]
将JDK版本降低至1.8，报错提示如下：
➜  Behinder_v3.0_Beta_4 java -jar Behinder.jar
错误: 找不到或无法加载主类 net.rebeyond.behinder.ui.Main

将JDK版本降低至1.6，报错提示如下：
Behinder_v3.0_Beta_4 java -XstartOnFirstThread -jar Behinder.jar
Exception in thread "Thread-1" java.lang.UnsupportedClassVersionError: net/rebeyond/behinder/ui/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

看了都是UI端出现了问题

**Comment by liao10086** [comment]
我也是Mac端 jdk1.8没有报错

**Comment by Arthur-Geng** [comment]
> 我也是Mac端 jdk1.8没有报错

  我是用brew安装的openjdk，不知道是不是这个原因。
